
server:
  # 默认服务端口
  port: 28087
  tomcat:
    uri-encoding: utf-8


# Spring配置
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  #        additional-paths: src/main/java #重启目录
  #        exclude: WEB-INF/**
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # Mysql
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis:
  type-aliases-package: com.testinsert.mvc.entity
  mapper-locations: classpath:mapper/*Mapper.xml


